### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by dciphered** [venveo/serverless-sharp#139]
We haven't seen any updates or mentions of further development activities happening in a while and I would like to get confirmation on whether further development and/or support is expected?

There are a number of EOL components associated with the last official release, some of which pose a security concern.

Appreciate any insights here.

**Comment by Mosnar** [comment]
@dciphered I'm not going to sugarcoat it since you deserve a straight answer - it's definitely not a priority for us since it doesn't pay the bills and it's an increasingly complicated project to maintain. It's something I'd love to spend more time on, but not something we can continuously commit resources to internally. This is emphasized as more inexpensive & self-hosted options for image optimization become available (e.g. Cloudflare Images, NextJS built-in optimization, AWS' original solution).

This project means a lot to me and has a special place in my heart, so I can't say it won't get updates, but I can't promise any timelines either - paid client work has to come first (unfortunately).

**Comment by dciphered** [comment]
Appreciate the candid response @Mosnar - makes absolute sense. I do hope to see further dev on the project in the future as it's a terrific solution overall!
