### ISSUE TITLE
White list width

### ISSUE THREAD

**Issue by gregBerthelot** [venveo/serverless-sharp#43]
Hi

Thanks for your great job. It should be very useful to provide a whitelist of width and serve only allowed dimensions. That should prevent abuse of Lambda and avoid other width than those used in eg `const srcSet = imageUrl + '?w=768 768w, ' + imageUrl + '?w=1024 1024w, ' + imageUrl + '?w=1366 1366w, ' + imageUrl + '?w=1600 1600w, ' + imageUrl + '?w=1920 1920w';`

Cheers

**Comment by Mosnar** [comment]
Hey @gregBerthelot Glad you're enjoying the project! Usually, I would suggest you use a CMS or site generator to generate all of the signed URLs at once. Do you have a particular use case where that's not practical?

I'm not a huge fan of whitelisting widths, as I think redeploying the application just to add a width is a bit heavy-handed and could quickly become messy. I think there are some compromises, but I'm interested to hear your response to my first note.

**Comment by gregBerthelot** [comment]
Security key is very nice feature but a bit complex to handle in a cms using srcset, dynamic url and siteID

Using a width whitelist corresponding to srcset w values seems in my opinion an easy way to avoid abuse of lambda function by malicious users from generating a lot of unwanted dimensions. 

Maybe this whitelist could be set in env variables instead of application itself to avoid redeploying.

**Comment by Mosnar** [comment]
We're going to discuss this internally and decide the best approach. One thing I want to note is that because this project follows the same API as Imgix, you can usually use any plugins and libraries built for Imgix to handle generating these signed image URLs for you. For example, we use Craft CMS a lot and often use the plugin [Imager](https://plugins.craftcms.com/imager-x) to automatically send all of the transforms to Serverless Sharp.
