### ISSUE TITLE
Not respecting original orientation on portrait photos

### ISSUE THREAD

**Issue by tyrauber** [venveo/serverless-sharp#67]
**Describe the bug**
Some images are being rotated 90 degrees regardless of original orientation.

**Expected behavior**
Expect the image to have the same orientation as the original in the S3 bucket.

**Screenshots**
[Original on S3]( https://serverless-sharp-test-env.s3.us-east-1.amazonaws.com/waterfall.jpeg)
![waterfall](https://user-images.githubusercontent.com/109972/81857938-3fa06a80-9563-11ea-944b-6f41af3fe76c.jpeg)

[Served by Api through Cloudfront with no resizing or orientation params](https://d2cifjbifbc1q8.cloudfront.net/waterfall.jpeg)
![waterfall](https://user-images.githubusercontent.com/109972/81857782-05cf6400-9563-11ea-9fb4-8ab9fe84f754.jpg)

**Versions**
Operating System:  AWS Node nodejs12.x
Serverless Sharp: 2.0.4

**Comment by Mosnar** [comment]
This is because the image is rotated via it's EXIF metadata rather than actually being rotated on an image data level. This metadata is stripped out during the compression process.
![image](https://user-images.githubusercontent.com/3810939/81858849-5b3f4d00-9532-11ea-9c69-d42ba9d00bfd.png)

The orientation property should definitely be preserved though, so let's call it a bug.

**Comment by Mosnar** [comment]
Fixed and just released 2.0.6

**Comment by tyrauber** [comment]
Ugh. Ok. Confirmed. Same image on Imgix preserves metadata... And resolved. Awesome. You, you I like.

What's the best way for me to deploy this fix to a live environment with the least amount of interruption?  Can I deploy just the function? ` serverless deploy function --function="index" --settings settings.yml --stage beta` Or do I need to rebuild the whole cloud formation stack?  What about with changing env variables? Or things like timeouts, concurrency, or memory?   Is it possible to deploy without touching the cloudfront distribution and cma?

I've already run into SSL issues with certs getting reissued and duplicate distributions trying to navigate updating live environments.

**Comment by Mosnar** [comment]
I've always just run `serverless deploy --stage <whatever> --settings <whatever>` and Serverless will handle versioning, configuration updates, and any new resources. It shouldn't remove any existing resources, simply update the existing lambda functions with a new version. If you run the command above with the `--verbose` flag, you can actually see what it's doing. 

That said, you *could* deploy only the changed functions like you suggested. This deployment process assume there were no changes to the stack itself and simply updates the lambda function's code with the latest version. 

I suggest you read through the official Serverless guide on deployment, here: https://www.serverless.com/framework/docs/providers/aws/guide/deploying/

As far as service interruption goes, my guess is that it would be imperceptible; particularly since Cloudfront will already have most of your images cached for most users. If zero downtime deployments are really important to you, it probably wouldn't be much work to implement something like this: https://github.com/davidgf/serverless-plugin-canary-deployments

Feel free to make a feature request, and know that pull requests are always welcome!
